var a=10;
document.write("The value of a is: ",a);
document.write("<br>");
document.write("...........................................");
document.write("<br>");
document.write("<br>");
document.write("<br>");
document.write("The value of ++a is:",++a);
document.write("<br>");
document.write("Now the value is: ",a);
document.write("<br>");
document.write("<br>");
document.write("The value of a++ is: ",a++);
document.write("<br>");
document.write("Now the value of a is: ",a);
document.write("<br>");
document.write("<br>");
document.write("The value of --a is: ",--a);
document.write("<br>");
document.write("Now the value is of a is: ",a);
document.write("<br>");
document.write("<br>");
document.write("The value of a-- is: ",a--);
document.write("<br>");
document.write("Now the value of a is: ",a);